"""added table

Revision ID: 0b2f0687ac41
Revises: b5feff09ac92
Create Date: 2025-07-23 07:00:03.186382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2f0687ac41'
down_revision: Union[str, Sequence[str], None] = 'b5feff09ac92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_observations', sa.Column('status', sa.String(), nullable=True), schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_observations', 'status', schema='ingestion_schema')
    # ### end Alembic commands ###
