"""base table for data collection

Revision ID: 8c55083f9b00
Revises: 
Create Date: 2025-07-29 08:41:30.798547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c55083f9b00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plate_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('region_code', sa.String(length=5), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('orientation', postgresql.ENUM('FRONT', 'REAR', name='vehicle_orientation'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion_schema'
    )
    op.create_index('idx_vehicle_observations_plate_hash', 'vehicle_observations', ['plate_hash'], unique=False, schema='ingestion_schema')
    op.create_index('idx_vehicle_observations_timestamp', 'vehicle_observations', ['timestamp'], unique=False, schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicle_observations_timestamp', table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_index('idx_vehicle_observations_plate_hash', table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_table('vehicle_observations', schema='ingestion_schema')
    # ### end Alembic commands ###
