"""added table

Revision ID: b5feff09ac92
Revises: 
Create Date: 2025-07-23 06:59:09.592232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5feff09ac92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=5), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion_schema'
    )
    op.create_index('idx_vehicle_observations_municipality', 'vehicle_observations', ['municipality'], unique=False, schema='ingestion_schema')
    op.create_index('idx_vehicle_observations_plate', 'vehicle_observations', ['plate'], unique=False, schema='ingestion_schema')
    op.create_index('idx_vehicle_observations_timestamp', 'vehicle_observations', ['timestamp'], unique=False, schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicle_observations_timestamp', table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_index('idx_vehicle_observations_plate', table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_index('idx_vehicle_observations_municipality', table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_table('vehicle_observations', schema='ingestion_schema')
    # ### end Alembic commands ###
