services:
  analytics-service:
    image: julianbierbaum/license-plate-system:analytics-service
    ports:
      - "5001:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${ANALYTICS_DB_USER}
      DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  auth-service:
    image: julianbierbaum/license-plate-system:auth-service
    ports:
      - "5002:5000"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      DOMAIN_NAME: ${DOMAIN_NAME}
      DOMAIN_LOCAL: ${DOMAIN_LOCAL}
      AD_USERNAME: ${AD_USERNAME}
      PASSWORD: ${PASSWORD}
      SERVER_IP: ${SERVER_IP}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  data-collection-service:
    image: julianbierbaum/license-plate-system:data-collection-service
    ports:
      - "5003:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DATA_COLLECTION_DB_USER}
      DB_PASSWORD: ${DATA_COLLECTION_DB_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
      SYNOLOGY_HOST: ${SYNOLOGY_HOST}
      SYNOLOGY_USERNAME: ${SYNOLOGY_USERNAME}
      SYNOLOGY_PASSWORD: ${SYNOLOGY_PASSWORD}
      API_KEY: ${PLATE_RECOGNIZER_API_KEY}
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  notification-service:
    image: julianbierbaum/license-plate-system:notification-service
    ports:
      - "5004:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${NOTIFICATION_DB_USER}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      ANALYTICS_SERVICE_URL: ${ANALYTICS_SERVICE_URL}
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  web-service:
    image: julianbierbaum/license-plate-system:web-service
    ports:
      - "3001:3000"
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      ANALYTICS_SERVICE_URL: ${ANALYTICS_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
    depends_on:
      db-migrator:
        condition: service_completed_successfully

  db-migrator:
    image: julianbierbaum/license-plate-system:db-migrator
    volumes:
      - ./db/alembic/versions:/app/alembic/versions
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${POSTGRES_ADMIN_USER}
      DB_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      ANALYTICS_DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      DATA_COLLECTION_DB_PASSWORD: ${DATA_COLLECTION_DB_PASSWORD}
      NOTIFICATION_DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERN}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: